config/routes.rb
EpicPizzaApp::Application.routes.draw do
  devise_for :users

  root :to => 'home_controller#index'

  resources :ingredients
  resources :pizzas do
    member do
      post 'order'
    end
  end
  resources :orders do
    member do
      post 'make'
      post 'pay'
      post 'deliver'
    end
  end

end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
      has_many :ingredient_associations, :dependent => :destroy, :before_add => :set_nested
      has_many :ingredients, :through => :ingredient_associations
      has_many :orders, :dependent => :destroy

      attr_accessible :name,
      					      :description,
      					      :ingredient_associations_attributes

      accepts_nested_attributes_for :ingredient_associations, :allow_destroy => true

      validates :name, :presence => true
      validates :description, :presence => true

      scope :currently_ordered_of_type, lambda { |pizza|
        where(:name => pizza.name, :status_cd => Order.open)
      }

      def price
      	ingredient_associations.reduce(0) { |acc, i| acc += (i.id ? i.total_price : 0) }
      end

    private
      def set_nested(ingredient_associations)
        ingredient_associations.pizza ||= self
      end
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  # GET /pizzas
  # GET /pizzas.json
  def index
    @pizzas = Pizza.all
    authorize! :index, Pizza

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pizzas }
    end
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
    @pizza = Pizza.find(params[:id])
    authorize! :show, @pizza

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pizza }
    end
  end

  # GET /pizzas/new
  # GET /pizzas/new.json
  def new
    @pizza = Pizza.new
    @ingredients = Ingredient.all
    authorize! :new, @pizza

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pizza }
    end
  end

  # GET /pizzas/1/edit
  def edit
    @pizza = Pizza.find(params[:id])
    @ingredients = Ingredient.all
    authorize! :edit, @pizza
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(params[:pizza])
    @ingredients = Ingredient.all
    authorize! :create, @pizza

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render json: @pizza, status: :created, location: @pizza }
      else
        format.html { render action: "new" }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pizzas/1
  # PUT /pizzas/1.json
  def update
    @pizza = Pizza.find(params[:id])
    authorize! :update, @pizza

    respond_to do |format|
      if @pizza.update_attributes(params[:pizza])
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza = Pizza.find(params[:id])
    authorize! :destroy, @pizza
    @pizza.destroy

    respond_to do |format|
      format.html { redirect_to pizzas_url }
      format.json { head :no_content }
    end
  end

  # POST /pizzas/1/order
  def order
    @pizza = Pizza.find(params[:id])

    @order = current_user.orders.last
    if not @order then
      @order = current_user.orders.build
    end

    case @order.status
      when :open
        @order.order_elements.build( :pizza => @pizza,
                                    :quantity => params[:order_element][:quantity] )
      when :made, :paid
        @order = nil
      when :closed
        @order = Order.new
        @order.order_elements.build( :pizza => @pizza,
                                    :quantity => params[:order_element][:quantity] )
        current_user.orders << @order
    end

    respond_to do |format|
      if @order then
        if @order.save
          format.html { redirect_to pizzas_path, notice: "Added pizza '#{@pizza.name}' to your order." }
          format.json { render json: @order, status: :created, location: @order }
        else
          format.html { render action: "new" }
          format.json { render json: @pizza.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to pizzas_path, alert: 'Please finalize current order first.' }
        format.js { redirect_to pizzas_path, alert: 'Please finalize current order first.' }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }        
      end
    end    
  end
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/views/pizzas/_form.html.haml
= semantic_form_for @pizza do |f|
  = f.inputs do
    = f.input :name
    = f.input :description
    %h3 Ingredients
    #ingredients
      = f.semantic_fields_for :ingredient_associations do |ingredient|
        = render 'ingredient_association_fields', :f => ingredient
      = link_to_add_association "Add an ingredient", f, :ingredient_associations, :class => 'btn btn-primary'
    = f.actions do
      = f.action :submit, :button_html => { :class => 'btn btn-success' }

app/views/pizzas/_ingredient_association_fields.html.haml
.nested-fields
  = f.inputs :name => 'Ingredient' do
    = f.input :pizza_id, :as => :hidden, :input_html => { :value => @pizza.id }
    = f.input :ingredient
    = f.input :quantity
    = link_to_remove_association "Remove this ingredient", f, :class => 'btn btn-danger'

app/views/pizzas/edit.html.erb
<h1>Editing pizza</h1>

<%= render 'form' %>

<%= link_to 'Show', @pizza, :class => 'btn btn-primary' %>
<%= link_to 'Back', pizzas_path, :class => 'btn btn-warning' %>

app/views/pizzas/index.html.erb
<h1>Listing pizzas</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pizzas.each do |pizza| %>
  <tr>
    <td><%= pizza.name %></td>
    <td><%= pizza.description %></td>
    <td><%= pizza.price %></td>
    <td><%= link_to 'Show', pizza, :class => 'btn btn-primary' %></td>
    <td><%= link_to 'Edit', edit_pizza_path(pizza), :class => 'btn btn-success' %></td>
    <td><%= if can? :destroy, pizza then (link_to 'Destroy', pizza, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger') end %></td>
    <td>
      <% if can? :make, Order then %>
        <%= render :partial => 'orders/inline_order', :locals => { :pizza => pizza } %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pizza', new_pizza_path, :class => 'btn btn-primary' %>

app/views/pizzas/new.html.erb
<h1>New pizza</h1>

<%= render 'form' %>

<%= link_to 'Back', pizzas_path, :class => 'btn btn-warning' %>

app/views/pizzas/show.html.erb
<p>
  <b>Name:</b>
  <%= @pizza.name %>
</p>

<p>
  <b>Description:</b>
  <%= @pizza.description %>
</p>

<p>
  <b>Ingredients:</b>
  <table class="table">
  		<tr>
	  		<th>Name</th>
	  		<th>Quantity</th>
	  		<th>Total Price</th>
	  	</tr>
		  <%- @pizza.ingredient_associations.each do |ia| %>
		  	<tr>
			  	<td><%= ia.ingredient.name %></td>
			  	<td><%= ia.quantity %></td>
			  	<td><%= ia.total_price %></td>
		  	</tr>
		  <% end %>
  		<td></td>
  		<td><b>Price:</b></td>
  		<td><%= @pizza.price %></td>
	</tbody>
  </table>
</p>

<%= link_to 'Edit', edit_pizza_path(@pizza), :class => 'btn btn-success' %>
<%= link_to 'Back', pizzas_path, :class => 'btn btn-warning' %>