config/routes.rb
EpicPizzaApp::Application.routes.draw do
  devise_for :users

  root :to => 'home_controller#index'

  resources :ingredients
  resources :pizzas do
    member do
      post 'order'
    end
  end
  resources :orders do
    member do
      post 'make'
      post 'pay'
      post 'deliver'
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_elements, :dependent => :destroy, :before_add => :set_nested
  has_many :pizzas, :through => :order_elements
  attr_accessible :quantity, :status

  as_enum :status, [:open, :made, :paid, :closed]

  scope :currently_open, where(:status_cd => Order.open)

  def total_price
  	order_elements.reduce(0) { |acc, i| acc += i.total_price }
  end

private
  def set_nested(order_elements)
    order_elements.order ||= self
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    # authorize! :index, Order
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])
    authorize! :show, @order

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  # def new
  #   @order = Order.new

  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @order }
  #   end
  # end

  # # GET /orders/1/edit
  # def edit
  #   @order = Order.find(params[:id])
  # end

  # # POST /orders
  # # POST /orders.json
  # def create
  #   @order = Order.new(params[:order])

  #   respond_to do |format|
  #     if @order.save
  #       format.html { redirect_to @order, notice: 'Order was successfully created.' }
  #       format.json { render json: @order, status: :created, location: @order }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @order.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PUT /orders/1
  # # PUT /orders/1.json
  # def update
  #   @order = Order.find(params[:id])

  #   respond_to do |format|
  #     if @order.update_attributes(params[:order])
  #       format.html { redirect_to @order, notice: 'Order was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @order.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  def make
    @order = Order.find(params[:id])
    authorize! :make, @order

    @order.update_attributes(:status => :made)

    respond_to do |format|
      format.html { redirect_to @order, notice: 'Your ourder was successfulyl made' }
    end
  end

  def pay
    @order = Order.find(params[:id])
    authorize! :pay, @order

    @order.update_attributes(:status => :paid)

    respond_to do |format|
      format.html { redirect_to @order, notice: 'Your ourder was successfulyl paid for' }
    end    
  end

  def deliver
    @order = Order.find(params[:id])
    authorize! :deliver, @order

    @order.update_attributes(:status => :closed)

    respond_to do |format|
      format.html { redirect_to @order, notice: 'Oder succesfully delivered' }
    end    
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :pizza %><br />
    <%= f.text_field :pizza %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :status_cd %><br />
    <%= f.number_field :status_cd %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/_inline_order.html.haml
= form_for OrderElement.new, :url => order_pizza_path(pizza), :method => :post do |f|
  = f.text_field :quantity, :style => 'width: 40px'
  = f.submit "Order", :class => 'btn btn-info'

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table class="table">
  <tr>
    <th>User</th>
    <th>Pizzas</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.user.username %></td>
    <td><%= order.order_elements.map { |el| "#{el.pizza.name} (#{el.quantity})"}.join(', ') %></td>
    <td><%= order.status %></td>
    <td><%= link_to 'Show', order, :class => 'btn btn-primary' %></td>
    <td><%= if order.status == :paid then link_to 'Deliver', deliver_order_path(order), :method => :post, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-success' end %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path, :class => 'btn btn-primary' %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p>
  <b>User:</b>
  <%= @order.user.username %>
</p>

<p>
  <b>Pizzas:</b>
  <ul>
    <% @order.order_elements.each do |element| %>
      <li><%= "#{element.pizza.name} (#{element.quantity})" %></li>
      <ul>
        <% element.pizza.ingredient_associations.each do |ia| %>
          <li><%= "#{ia.ingredient.name} (#{element.quantity})" %></li>
        <% end %>
      </ul>
    <% end %>
  </ul>
</p>

<p>
  <b>Status:</b>
  <%= @order.status %>
</p>

<% if @order.status == :made then %>
  <%= link_to 'Pay', pay_order_path(@order), :method => :post, :class => 'btn btn-success' %>
<% end %>
<% if @order.status == :paid and can? :deliver, @order then %>
  <%= link_to 'Deliver', deliver_order_path(@order), :method => :post, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-success' %>
<% end %>
<%= link_to 'Back', orders_path, :class => 'btn btn-warning' %>