config/routes.rb
EpicPizzaApp::Application.routes.draw do
  devise_for :users

  root :to => 'home_controller#index'

  resources :ingredients
  resources :pizzas do
    member do
      post 'order'
    end
  end
  resources :orders do
    member do
      post 'make'
      post 'pay'
      post 'deliver'
    end
  end

end

app/views/layouts/_notices.html.erb
<% if notice then %>
  <div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= notice %>
  </div>
<% end%>
<% if alert then %>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= alert %>
  </div>
<% end%>

app/views/layouts/_order.html.haml
- if @users_order
  %table.table
    %tr
      %th Name
      %th Qty
      %th Price
    - @users_order.order_elements.each do |element|
      %tr
        %td= element.pizza.name
        %td= element.quantity
        %td= element.total_price
    %tr
      %td
      %td
        %b Total:
      %td= @users_order.total_price
  - case @users_order.status
    - when :open
      = link_to make_order_path(@users_order), :method => :post, :class => 'btn btn-success' do
        Make order
    - when :made
      = link_to pay_order_path(@users_order), :method => :post, :class => 'btn btn-success' do
        Pay
    - when :paid
      %b
        Your order has been paid, please wait for it to be delivered
- else
  You have no open order

app/views/layouts/_sidebar.html.haml
.well
  %h5 Your Order
  - if user_signed_in?
    = render 'layouts/order'
  - else
    You need to be logged in to order:

    = form_tag user_session_path do
      = text_field_tag 'user[email]', "", :placeholder => 'Username'
      = password_field_tag 'user[password]', "",  :placeholder => 'Password'
      %br/
      = check_box_tag 'user[remember_me]'
      = label_tag 'user[remember_me]', 'Remember me'
      %button.btn.btn-primary Sign in
      %br/
      = link_to "Sign up", new_user_registration_path
      %br/
      = link_to "Forgot your password?", new_password_path('user')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EpicPizzaApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">      
        <a class="brand" href="/">EpicPizzaApp</a>
        <ul class="nav">
          <li><%= link_to "Pizzas", pizzas_path %></li>
          <li><%= link_to "Ingredients", ingredients_path if can? :manage, Ingredient %></li>
          <li><%= link_to "Orders", orders_path if can? :index, Order %></li>
        </ul>
        <div class="container-fluid pull-right">
          <ul class="nav">
            <% if current_user && current_user.admin? then %>
              <li><a href="#" style="color: red;">JESTĘ ADMINĘ</a></li>
            <% end %>
            <li><%= if user_signed_in? then link_to("Logout", destroy_user_session_path, :method => :delete) else link_to("Login", new_user_session_path) end %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <br />
  <br />
  <br />
  <div id="notices">
    <%= render 'layouts/notices' %>
  </div>
  <div class="row-fluid">
    <% if @display_sidebar then %>
      <div class="span3">
        <!--Sidebar content-->
        <%= render 'layouts/sidebar' %>
      </div>
    <% end %>
    <div class=<%= @display_sidebar  ? "span9" : "span12" %>>
      <!--Body content-->
      <%= yield %>
    </div>
  </div>  

  <hr />
  <footer>
    EpicPizzaApp, 2012
  <footer>
</div>
</body>
</html>